### PR TITLE
Correct the limits on XYZ model

### PR DESCRIPTION
**Pull request by technobuddha**
The limits are incorrect on the XYZ model (X: 100, Y: 100, Z: 100)
The correct limits are X: 95.047, Y: 100, Z: 108.833.

When you convert RGB(255, 255, 255) (white):
The current code returns: XYZ(95.047, 100, 100).
The correct answer is:  XYZ(95.047, 100, 108.833).

This can be verified using either:
http://colormine.org/convert/rgb-to-xyz
https://www.nixsensor.com/free-color-converter/     (be sure to set the input and output Illuminant to D65 2°)

### CODE REVIEW

**Comment by Qix-** [comment]
Hi there - admittedly I'm not super well-versed in XYZ. Can you explain a bit more the reasoning here?

**Comment by technobuddha** [comment]
?Hi,


It's complicated...


When you convert to XYZ, it takes an illumination factor, which involves several "magic" numbers:?

?    const x = (r * 0.4124564) + (g * 0.3575761) + (b * 0.1804375);

    const y = (r * 0.2126729) + (g * 0.7151522) + (b * 0.072175);?

  const z = (r * 0.0193339) + (g * 0.119192) + (b * 0.9503041);

These numbers correspond to the standard "D65 2deg" illumination.


If you add the three number for X, you get 0.95047, for Y you get 1.0000001 for Z 1.08883.  Which when multiplied by 100 is the range limit for the XYZ conversion (one of the three Y numbers is off by 0.0000001 but I don't know which one :) ).


You can also see these number reflected in the conversion from XYZ to LAB:

    x /= 95.047;?

    y /= 100;?

    z /= 108.883;


The XYZ color space is a strange beast, it's only real purpose it that it's easier to convert to XYZ and then to LAB which is useful for comparing colors.


That's about the limit of my understanding.


Phil

________________________________

**Comment by Qix-** [comment]
The 0.0000001 is probably an IEEE-754 rounding error, it's insignificant enough to ignore.

This is interesting, thank you for the writeup and sorry for the delay.

**Comment by Qix-** [comment]
Changes ultimately landed in d00bd1aa371c8313dd4fa29140b0249984ec70fc and will be released as `4.2.3`. Thanks again :)

**Pull request closed without merging**
