### PR TITLE
Adds travis jobs on ppc64le

### PR DESCRIPTION
**Pull request by dineshks1**
This PR adds power support on travis.

### CODE REVIEW

**Comment by Qix-** [comment]
No thanks. This is the 4th PR I've seen you make trying to add this. I'm not sure the intention, but this is not something that is needed for node projects that don't have architecture-dependent code.

**Comment by dineshks1** [comment]
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing,For more info tag @gerrith3.

**Comment by dineshks1** [comment]
Please review this merge.

**Comment by Qix-** [comment]
That makes no sense. `color` is not an Ubuntu package. It's not meant to be part of a distribution. You install it via npm or yarn or something of the sort.

You've already tagged that person - I don't know who they are, and I don't understand how a **platform independent javascript library** has any bearing on Ubuntu releases. There's absolutely no difference in testing against a different architecture. Bugs arising from such a difference would mean there is a bug in **node.js itself**, not this library.

This is a non-starter - you sem to have a misconception about how architectures and javascript work together.

**Pull request closed without merging**
