### PR TITLE
Renamed boolean methods

### PR DESCRIPTION
**Pull request by felixsanz**
This makes more sense in my opinion

### CODE REVIEW

**Comment by felixsanz** [comment]
What does this error mean? Looks like CI is testing for 1.0.3, which of course lacks of the method

**Comment by levithomason** [comment]
```
/home/travis/build/Qix-/color/index.js
  299:10  error  "isDark" is not defined  no-undef
```

At line `299` in `index.js` there is use of an undefined value `isDark`.  It should be `this.isDark`:

```diff
-return isDark();
+return this.isDark();
```

**Comment by sindresorhus** [comment]
@felixsanz ⬆️

**Comment by felixsanz** [comment]
@sindresorhus Please merge #137

**Pull request closed without merging**
