### PR TITLE
contast ratio level AAA is above 7:1

### PR DESCRIPTION
**Pull request by shfshanyue**
> https://www.w3.org/TR/WCAG/#contrast-enhanced
>
> The visual presentation of [text](https://www.w3.org/TR/WCAG/#dfn-text) and [images of text](https://www.w3.org/TR/WCAG/#dfn-images-of-text) has a [contrast ratio](https://www.w3.org/TR/WCAG/#dfn-contrast-ratio) of at least 7:1, except for the following:

### CODE REVIEW

**Comment by Qix-** [comment]
Good catch. That's been lurking for 6 years. Will merge/release when CI is green.

**Comment by shfshanyue** [comment]
ok, it's done

**Comment by Qix-** [comment]
Oh sorry, the linting problems shouldn't have happened. Not sure why they did anyway.

**Comment by Qix-** [comment]
The actual commit landed in `406d384e39cdc7d7fceabf10f34209f27d57376c` and will be released as `4.2.2` shortly :) I addressed the linting issues separately.

Thanks for the PR!

**Pull request closed without merging**
