### PR TITLE
Add: ahex and hexa

### PR DESCRIPTION
**Pull request by TheRealSyler**
#125
never seen anyone use ahex before, but im pretty sure my implementation is correct, i didn't add tests because i don't know how they work yet, its on my list of things to learn that i don't really want to learn.

i also ran `npm audit fix` which increased the `xo`  version to  `0.24.0`

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Why was this closed @TheRealSyler? I could really use this feature 🙂

**Comment by TheRealSyler** [comment]
@rijkvanzanten because i don't want it in my pull request menu thingy, and this will probably never me merged.

**Comment by Qix-** [comment]
No reason to close it. I don't have a lot of bandwidth to allot to node.js projects at the moment, sadly - but I wouldn't say never.

One of the main reasons why `color` has gone a bit un-touched is that the API is creeping into a huge mess. Working with models and the confusion around e.g. `.whiten()` are a _really_ hard problem to solve. I've been thinking about it for the better part of 2 years now.

I'm really hesitant on adding any new API methods until I can figure out a good way to make an expressive and intuitive API that doesn't sacrifice any sort of performance.

**Comment by rijkvanzanten** [comment]
I hear you! And with ~8 million downloads a week, you definitely don't want to rush and push anything without being happy with it. Let me know if you have any specific unknowns you'd like some different perspectives on. I'm not too familiar with the internals of the project, but I'm more than happy to help out where I can

**Comment by jchook** [comment]
+1 I use `color` on a daily basis and would happily invest time into it.

**Pull request closed without merging**
